// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMwzrJ0GLMOh4eCfTxWpb1EyRUq1cw3uc',
    appId: '1:1029253004219:web:705913a928c0aff491629e',
    messagingSenderId: '1029253004219',
    projectId: 'green-mile-24fb2',
    authDomain: 'green-mile-24fb2.firebaseapp.com',
    storageBucket: 'green-mile-24fb2.appspot.com',
    measurementId: 'G-R9H5E8BQ4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUZmb9dGbpKVXu8ki0_HQuMba0hDrYlDU',
    appId: '1:1029253004219:android:332c69d99d24fe1791629e',
    messagingSenderId: '1029253004219',
    projectId: 'green-mile-24fb2',
    storageBucket: 'green-mile-24fb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARJ8ATliVYIke4VGYU7Yzt-FpCWk-RX3o',
    appId: '1:1029253004219:ios:697dac3748ffc84491629e',
    messagingSenderId: '1029253004219',
    projectId: 'green-mile-24fb2',
    storageBucket: 'green-mile-24fb2.appspot.com',
    iosClientId: '1029253004219-sis1rs69n4menjismpugecfqbncmj7eh.apps.googleusercontent.com',
    iosBundleId: 'com.example.greenMile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARJ8ATliVYIke4VGYU7Yzt-FpCWk-RX3o',
    appId: '1:1029253004219:ios:697dac3748ffc84491629e',
    messagingSenderId: '1029253004219',
    projectId: 'green-mile-24fb2',
    storageBucket: 'green-mile-24fb2.appspot.com',
    iosClientId: '1029253004219-sis1rs69n4menjismpugecfqbncmj7eh.apps.googleusercontent.com',
    iosBundleId: 'com.example.greenMile',
  );
}
